dist: trusty
language: cpp
sudo: false

common_sources: &all_sources
  - ubuntu-toolchain-r-test
  - llvm-toolchain-trusty
  - llvm-toolchain-trusty-3.9
  - llvm-toolchain-trusty-4.0
  - llvm-toolchain-trusty-5.0
  - llvm-toolchain-trusty-6.0
  - sourceline: 'ppa:mhier/libboost-latest'

matrix:
  exclude: # On OSX g++ is a symlink to clang++ by default
    - os: osx
      compiler: gcc

  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: *all_sources
          packages: ['gcc-7', 'g++-7', 'cmake', 'boost1.67']
      env: CCOMPILER='gcc-7' CXXCOMPILER='g++-7'

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: *all_sources
          packages: ['clang-6.0', 'libstdc++-6-dev', 'cmake', 'boost1.67']
      env: CCOMPILER='clang-6.0' CXXCOMPILER='clang++-6.0'

    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env: CCOMPILER='clang' CXXCOMPILER='clang++'

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake || brew upgrade cmake
    fi

script:
  - export CC=$CCOMPILER
  - export CXX=$CXXCOMPILER
  - cmake --version
  - ${CXX} -v
  - (mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build . && ctest -V .)
