dist: trusty
language: cpp
sudo: false

common_sources: &all_sources
  - ubuntu-toolchain-r-test
  - llvm-toolchain-trusty
  - llvm-toolchain-trusty-3.9
  - llvm-toolchain-trusty-4.0
  - llvm-toolchain-trusty-5.0
  - llvm-toolchain-trusty-6.0
  - sourceline: 'ppa:mhier/libboost-latest'

matrix:
  exclude: # On OSX g++ is a symlink to clang++ by default
    - os: osx
      compiler: gcc

  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: *all_sources
          packages: ['gcc-7', 'g++-7', 'cmake', 'boost1.67']
      env: MYCC='gcc-7' MYCXX='g++-7'

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: *all_sources
          packages: ['gcc-6', 'g++-6', 'cmake', 'boost1.67']
      env: MYCC='gcc-6' MYCXX='g++-6'

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: *all_sources
          packages: ['gcc-5', 'g++-5', 'cmake', 'boost1.67']
      env: MYCC='gcc-5' MYCXX='g++-5'

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: *all_sources
          packages: ['clang-6.0', 'libstdc++-6-dev', 'cmake', 'boost1.67']
      env: MYCC='clang-6.0' MYCXX='clang++-6.0'

    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env: MYCC='clang' MYCXX='clang++'

    - os: osx
      osx_image: xcode9.3
      compiler: clang
      env: MYCC='clang' MYCXX='clang++'

    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env: MYCC='clang' MYCXX='clang++'

    - os: osx
      osx_image: xcode9.1
      compiler: clang
      env: MYCC='clang' MYCXX='clang++'

    - os: osx
      osx_image: xcode9
      compiler: clang
      env: MYCC='clang' MYCXX='clang++'

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env: MYCC='clang' MYCXX='clang++'

before_script:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.12/cmake-3.12.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${PWD}/cmake/bin:${PATH}
    fi

script:
  - export CC=${MYCC}
  - export CXX=${MYCXX}
  - cmake --version
  - ${CXX} -v
  - (mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build . && ctest -V .)
